### ISSUE TITLE
Extra border around the code block

### ISSUE THREAD

**Issue by mrprofessor** [gongzhitaao/orgcss#14]
orgcss is showing an extra border around the code block

my org file:
```org
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>

* Source code
** python

#+BEGIN_SRC python

import os

print("Hello people")

#+END_SRC
```
#### Result
![image](https://user-images.githubusercontent.com/11652364/84314628-01a85d80-ab86-11ea-99e0-09ef06aa9cfb.png)

I am using org version **9.4**

**Comment by mrprofessor** [comment]
@gongzhitaao ^^^

**Comment by gongzhitaao** [comment]
Thank you @mrprofessor for reporting this.  Yes, I saw this bug.  Sorry I didn't reply earlier.  I was busy with other work stuff.  I will investigate sometime this week.

**Comment by mrprofessor** [comment]
Thank you @gongzhitaao

**Comment by gongzhitaao** [comment]
The current orgmode stable version is 9.3.7, and I couldn't reproduce this style error.  Are you using the orgmode dev version?

**Comment by pjhuxford** [comment]
I have the same issue on Org 9.3 and Org 9.3.6. I was able to work around this by adding the line `#+options: html-style:nil` to my org document, however this makes `src` blocks with no language render with no border. You can obtain a border for them by adding a dummy language to the `src` block, e.g.

```
#+begin_src fake-language
fake code
#+end_src
```

**Comment by gongzhitaao** [comment]
@pjhuxford Thanks, let me try reproducing this.

**Comment by shichaoxia** [comment]
Using `#+HTML_HEAD` in an org file then 'C-c C-e h h' (org-export-dispatch html) appends superfluous css codes generated automatically by org mode.   Inside that code, `pre { border: 1px solid #ccc; }` is defined. That's the reason extra border appears. 

Remove the org generated css code, or remove `.org-src-container { border: 1px solid #ccc;`.

**Comment by gongzhitaao** [comment]
@shichaoxia Thanks, that makes sense.  I was wondering why I couldn't reproduce this as I configure this in my init file.
