### ISSUE TITLE
Fixing the incorrect back reference for BibTex

### ISSUE THREAD

**Issue by Anirudh-C** [gongzhitaao/orgcss#17]
In the [known issues](https://gongzhitaao.org/orgcss/#sec:known-issues) section the back reference issue is fixed during the build time? How would I apply the same fix?

**Comment by gongzhitaao** [comment]
The way I used is as follows: replace every `ref.html` with `index.html` in `ref_bib.html`.  This line https://github.com/gongzhitaao/orgcss/blob/master/gulpfile.js#L38 chooses the file `ref_bib.html`, and these line https://github.com/gongzhitaao/orgcss/blob/master/gulpfile.js#L48,L50 do the replacement.

**Comment by Anirudh-C** [comment]
Cool! Got it. Thanks
