### ISSUE TITLE
Load MathJax packages

### ISSUE THREAD

**Issue by MeetThePatel** [gongzhitaao/orgcss#24]
Hello,

I am a user of org-roam-server, which uses this package. I've been having an issue with the MathJax rendering, as can be seen in the following screenshot: 

![Screen Shot 2021-07-06 at 3 06 36 PM](https://user-images.githubusercontent.com/11304993/124653821-c43b0000-de6b-11eb-91cc-6944b40ad5f1.png)

What is happening is that I am using commands from the Physics and AMS packages in LaTeX, and this works inside of org-mode because of my latex_header preamble. However, when exporting to html/css using MathJax, it doesn't use the Physics or AMS packages (or any other package, for that matter).

However, I think that there is a fix for this issue. MathJax has extensions that can be enabled (http://docs.mathjax.org/en/latest/input/tex/extensions/). How exactly would one go about enabling these in orgcss be default?

Thanks

**Comment by gongzhitaao** [comment]
Hey @MeetThePatel ,

According to 
1. https://orgmode.org/manual/Math-formatting-in-HTML-export.html and
2. http://docs.mathjax.org/en/latest/web/configuration.html#configuration-using-an-in-line-script

I think there are two ways to load extra extensions:
1. Customize this Emacs variable `org-html-mathjax-template` to load extra extensions.
2. Use the `\require` macro `\(\require{color}\)` to load the extensions at runtime.  See http://docs.mathjax.org/en/latest/input/tex/extensions.html#loading-extensions-at-run-time for more details.

Let me know if either one works for you.

**Comment by gongzhitaao** [comment]
I will close this for now.  Feel free to reopen if needed.
