### ISSUE TITLE
No spacing between paragraphs?

### ISSUE THREAD

**Issue by lukego** [gongzhitaao/orgcss#6]
I really like your CSS!

I am surprised at the lack of spacing between paragraphs though. Is that intentional? I find it hard to see where one ends and the next starts.

**Comment by gongzhitaao** [comment]
Actually, It WAS intentional.  I remembered that I removed the margin of all `<p>` elements on purpose, but I forgot why.  It is probably because the previous versions of `org-mode` use `<p>` arbitrarily. But I'm not sure.  It seems much more readable with a margin now.
Thank you!

**Comment by lukego** [comment]
That's awesome, thanks!
