### ISSUE TITLE
Little typo in index.org & margin disapear using org 9.3

### ISSUE THREAD

**Issue by reyman** [gongzhitaao/orgcss#9]
Hi,
I'm trying to generate the index.org using provided org.css files, but there is a little typo in index.org : 

`#+HTML_HEAD: <link id="pagestyle" rel="stylesheet" type="text/css" href="org.css"/>`

corrected to 

`#+HTML_HEAD: <link id="pagestyle" rel="stylesheet" type="text/css" href="css/org.css"/>`

When i compile using org version 9.3, left margin disapear, see the screen shoot joined
![Screenshot_2019-11-27 CSS for Org-exported HTML](https://user-images.githubusercontent.com/466329/69711969-4a288e00-1102-11ea-91ac-4ba6e18a5945.png)

**Comment by gongzhitaao** [comment]
Hi Rayman,

1. The css path is `org.css` instead of `css/org.css`.  The `docs` is the serving directory where `index.html` and `org.css` live in the same level.
2. I will look into the margin thing.  Maybe orgmode changes again :thinking: Thanks

**Comment by gongzhitaao** [comment]
Hi @reyman which browser are you using?  I could not reproduce the problem.
